# Generated by Django 5.2.1 on 2025-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_csidata_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="csidata",
            name="port_time_stamp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
